#!/bin/bash
#SBATCH --job-name=RGI_AllGenomes
#SBATCH --output=RGI_AllGenomes.out
#SBATCH --error=RGI_AllGenomes.err
#SBATCH --time=48:00:00                 
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --mem=64G
#SBATCH --partition=k2-lowpri           

source /mnt/scratch2/users/40296019/conda/etc/profile.d/conda.sh
conda activate rgi_blast_env

INPUT_DIR="/users/40296019/sharedscratch/projectdata/raw_genomes"
OUTPUT_DIR="/users/40296019/sharedscratch/projectdata/raw_genomes/RGI_Results"

mkdir -p "$OUTPUT_DIR"

cd "$INPUT_DIR" 

for i in *.fna; do
    base_name=$(basename "$i" .fna)
    output_subdir="$OUTPUT_DIR/${base_name}_RGI"
    mkdir -p "$output_subdir"

    rgi main --input_sequence "$i" \
             --output_file "$output_subdir/${base_name}_RGI" \
             --num_threads 8 \
             --local 
done

