#!/bin/bash

#SBATCH --job-name=Fasttree_KP
#SBATCH --error=Fasttree.error
#SBATCH --output=Fasttree.log
#SBATCH --partition=k2-medpri
#SBATCH --time=24:00:00
#SBATCH --nodes=1
#SBATCH --mem=124G
#SBATCH --cpus-per-task=16

fasttree -nt -gtr < core_gene_alignment.aln > Kpneumoniae_phylo_18Feb25.treefile
